@extends('themes.default.auth.layout')

@section('title')
    @lang('l.Two-Factor Authentication')
@endsection

@section('description')
@endsection

@section('page-css')
@endsection

@section('content')
    <main class="auth-minimal-wrapper">
        <div class="auth-minimal-inner">
            <div class="minimal-card-wrapper">
                <div class="card mb-4 mt-5 mx-4 mx-sm-0 position-relative">
                    <div
                        class="wd-50 bg-white p-2 rounded-circle shadow-lg position-absolute translate-middle top-0 start-50">
                        <img src="{{ asset($settings['favicon']) }}" alt="" class="img-fluid">
                    </div>
                    <div class="card-body p-sm-5">
                        <h2 class="fs-20 fw-bolder mb-4">
                            @lang('l.Two-Factor Authentication')
                            <i class="fa-brands fa-google ms-2"
                                style="background: linear-gradient(90deg, #4285f4 25%, #34a853 25%, #34a853 50%, #fbbc05 50%, #fbbc05 75%, #ea4335 75%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;"></i>
                        </h2>

                        <div class="alert alert-info mb-4">
                            @lang('l.Please enter the 6-digit code generated by your authenticator app to complete the two-factor authentication process.')
                        </div>

                        @if (session('error'))
                            <div class="alert alert-danger mb-4">
                                {{ session('error') }}
                            </div>
                        @endif

                        @if ($errors->any())
                            <div class="alert alert-danger mb-4">
                                {{ $errors->first() }}
                            </div>
                        @endif

                        <form method="POST" action="{{ route('2fa.verify') }}" class="w-100 mt-4 pt-2">
                            @csrf
                            <div class="mb-4">
                                <input type="text" name="code" id="code" class="form-control" required
                                    maxlength="6" pattern="\d{6}" placeholder="000000"
                                    style="letter-spacing: 0.3em; text-align: center; font-size: 1.2em;">
                            </div>

                            <div class="mt-5">
                                <button type="submit" class="btn btn-lg btn-primary w-100">
                                    <i class="fas fa-shield-alt me-2"></i>
                                    {{ __('l.Verify') }}
                                </button>
                            </div>
                        </form>

                        <div class="mt-5 text-center">
                            <small class="text-muted">@lang('l.or')</small>
                            <form method="POST" action="{{ route('logout') }}" class="mt-2">
                                @csrf
                                <button type="submit" class="btn btn-link text-danger">
                                    <i class="fas fa-sign-out-alt me-1"></i>
                                    @lang('l.Logout')
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

@section('page-scripts')
@endsection
